PJ_Airlines/Models/Flight.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PJ_Airlines.Models
{
    public class Flight
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

PJ_Airlines/Models/Passenger.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PJ_Airlines.Models
{
    public class Passenger
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

PJ_Airlines/ViewModels/RandomFlightViewModel.cs
using PJ_Airlines.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PJ_Airlines.ViewModels
{
    public class RandomFlightViewModel
    {
        public Flight Flight { get; set; }
        public List<Passenger> Passengers { get; set; }
    }
}

PJ_Airlines/Controllers/FlightsController.cs
using PJ_Airlines.Models;
using PJ_Airlines.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PJ_Airlines.Controllers
{
    public class FlightsController : Controller
    {
        // GET: Flights
        public ActionResult Index()
        {
            var flights = GetFlights();
            return View(flights);
        }

        public IEnumerable<Flight> GetFlights()
        {
            return new List<Flight> ()
            {
                new Flight{Id = 1, Name ="FR 123" },
                new Flight{Id = 2, Name="IE 082" }
            };          
        }

        public ActionResult Details (int id)
        {
            var flight = GetFlights().SingleOrDefault(x => x.Id == id);
            if (flight == null)
            {
                return Content("Flight does not exist");
            }
            return View(flight);
        }

        public ActionResult Random()
        {
            var flight = new Flight()
            {
                Id = 1,
                Name = "EI 161"
            };

            
            var passengers = new List<Passenger>
            {
                new Passenger{Id = 1, Name = "Simon"},
                new Passenger{Id=2, Name="Padraig"}
            };


            var viewModel = new RandomFlightViewModel
            {
                Flight = flight,
                Passengers = passengers
            };

            return View(viewModel);
        }
    }
}

PJ_Airlines/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PJ_Airlines.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PJ_Airlines/Controllers/PassengersController.cs
using PJ_Airlines.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PJ_Airlines.Controllers
{
    public class PassengersController : Controller
    {
        // GET: Passengers
        public ActionResult Index()
        {
            var passengers = GetPassengers();
            return View(passengers);
        }

        private IEnumerable<Passenger> GetPassengers()
        {
            return new List<Passenger>()
            {
                new Passenger{Name="John Smith", Id=1},
                new Passenger{Name="Mary Williams", Id=2}
            };
        }
        public ActionResult Details(int id)
        {
            var passenger = GetPassengers().SingleOrDefault(c => c.Id == id);

            if (passenger == null)
            {
                return HttpNotFound();
            }
            return View(passenger);
        }
    }
}

PJ_Airlines/Views/Flights/Details.cshtml
@model PJ_Airlines.Models.Flight
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<h2>@Model.Id</h2>

PJ_Airlines/Views/Flights/Index.cshtml
@model IEnumerable<PJ_Airlines.Models.Flight>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Flights</h2>

@if (!Model.Any())
{
    <p>We do not have any Flights currently</p>
}
else
{
    <table class="table table-borderd table-hover">
        <thead>
            <tr>
                <th>Flights</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var flight in Model)
            {
                <tr>
                    <td>@Html.ActionLink(flight.Name, "Details", "Flights", new { id = flight.Id }, null)</td>
                </tr>
            }
        </tbody>
    </table>
}

PJ_Airlines/Views/Flights/Random.cshtml
@model PJ_Airlines.ViewModels.RandomFlightViewModel
@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Flight.Name</h2>

@if (Model.Passengers.Count == 0)
{
    <p>There are no passengers</p>
}

else

{
    <ul>
        @foreach (var passenger in Model.Passengers)
        {
            <li>@passenger.Name</li>
            <li>@passenger.Id</li>
        }
    </ul>
}

PJ_Airlines/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PJ_Airlines/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PJ_Airlines/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome to PJ Airlines</h1>
    <p class="lead">Click on Flights and Passengers in the nav bar above to view some stuff!</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PJ_Airlines/Views/Passengers/Details.cshtml
@model PJ_Airlines.Models.Passenger
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>

PJ_Airlines/Views/Passengers/Index.cshtml
@model IEnumerable<PJ_Airlines.Models.Passenger>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Passengers</h2>
@if (!Model.Any())
{
    <p>We do not have any passengers</p>
}

else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Passengers</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var passenger in Model)
            {
                <tr>
                    <td>@Html.ActionLink(passenger.Name, "Details", "Passengers", new { id = passenger.Id }, null)</td>
                </tr>
            }
        </tbody>
    </table>
}

PJ_Airlines/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PJ_Airlines</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PJ_Airlines/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">           
            @Html.ActionLink("PJ_Airlines name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Flights", "Index", "Flights")</li>
                <li>@Html.ActionLink("Passengers", "Index", "Passengers")</li>
            </ul>
        </div>
    </div>
</div>